name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latestasdfasdf
    container: debian:oldstable

    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
      
      - name: install build tools
        run: apt-get update && apt-get install -y build-essential yasm cmake libtool libc6 libc6-dev unzip wget git autoconf libtool libssl-dev nasm jq libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig1-dev libbz2-dev g++-mingw-w64 gcc-mingw-w64
        
      - name: create install directory
        run: mkdir installdir

      - name: Configure
        run: ./configure --prefix=${GITHUB_WORKSPACE}/installdir --disable-shared --enable-static --enable-pic --extra-cflags="-fPIC -fvisibility=hidden -O2 -g" --extra-cxxflags="-fPIC -fvisibility=hidden -O2 -g" --extra-ldflags="-fPIC"

      - name: Compile ffmpeg
        run: make

      - name: Install ffmpeg
        run: make install
         
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-linux
          path: |
            installdir/lib/
            installdir/include/
          retention-days: 90
          overwrite: true

      - name: Clean
        run: make clean
        
      - name: Configure for Windows
        run: ./configure --prefix=${GITHUB_WORKSPACE}/installdir --disable-shared --enable-static --enable-pic --extra-cflags="-fPIC -fvisibility=hidden -O2 -g" --extra-cxxflags="-fPIC -fvisibility=hidden -O2 -g" --extra-ldflags="-fPIC" --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32-
      
      - name: Compile ffmpeg for Windows
        run: make

      - name: Install ffmpeg for Windows
        run: make install
         
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-win
          path: |
            installdir/lib/
            installdir/include/
          retention-days: 90
          overwrite: true

  build-macos:
    runs-on: macos-13adfasdfasdf
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
      
      - name: Install build tools
        run: brew install yasm nasm automake
      
      - name: Create install directory
        run: mkdir installdir
      
      - name: Configure
        run: ./configure --prefix=${GITHUB_WORKSPACE}/installdir --disable-shared --enable-static --enable-pic --extra-cflags="-fPIC -fvisibility=hidden -O2 -g" --extra-cxxflags="-fPIC -fvisibility=hidden -O2 -g" --extra-ldflags="-fPIC"
      
      - name: Compile FFmpeg
        run: make
      
      - name: Install FFmpeg
        run: make install
      
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-macos
          path: |
            ${{ github.workspace }}/installdir/lib/
            ${{ github.workspace }}/installdir/include/
          retention-days: 90
          overwrite: true

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - name: Install YASM
        run: |
          curl -L https://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -o yasm.exe
          mkdir tools
          move yasm.exe tools\yasm.exe
          echo %CD%\tools >> %GITHUB_PATH%
      
      - name: Create install directory
        run: mkdir installdir
      
      - name: Set environment variables
        run: |
          echo "Setting up build environment..."
          set INCLUDE=%INCLUDE%;%CD%\installdir\include
          set LIB=%LIB%;%CD%\installdir\lib
      
      - name: Configure FFmpeg
        run: |
          configure ^
          --toolchain=msvc ^
          --target-os=win64 ^
          --arch=x86_64 ^
          --prefix=%CD%\installdir ^
          --disable-shared ^
          --enable-static ^
          --enable-asm ^
          --enable-yasm ^
          --disable-doc ^
          --disable-ffplay ^
          --disable-ffprobe ^
          --disable-debug ^
          --extra-cflags="-MT -O2" ^
          --extra-ldflags="-LTCG"
      
      - name: Build FFmpeg
        run: nmake
      
      - name: Install FFmpeg
        run: nmake install
      
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-windows-msvc
          path: |
            installdir/lib/
            installdir/include/
          retention-days: 90
          overwrite: true

