name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: debian:oldstable

    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
      
      - name: install build tools
        run: apt-get update && apt-get install -y build-essential yasm cmake libtool libc6 libc6-dev unzip wget git autoconf libtool libssl-dev nasm jq libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig1-dev libbz2-dev
        
      - name: create install directory
        run: mkdir installdir

      - name: Configure
        run: ./configure --prefix=${GITHUB_WORKSPACE}/installdir --disable-shared --enable-static --enable-pic --extra-cflags="-fPIC -fvisibility=hidden -O2 -g" --extra-cxxflags="-fPIC -fvisibility=hidden -O2 -g" --extra-ldflags="-fPIC"

      - name: Compile ffmpeg
        run: make

      - name: Install ffmpeg
        run: make install
         
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-linux
          path: |
            ${{ github.workspace }}/installdir/lib/
            ${{ github.workspace }}/installdir/include/
          retention-days: 90
          overwrite: true

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
      
      - name: Install build tools
        run: brew install yasm nasm autoconf automake libtool pkg-config
      
      - name: Create install directory
        run: mkdir installdir
      
      - name: Configure
        run: ./configure --prefix=${GITHUB_WORKSPACE}/installdir --disable-shared --enable-static --enable-pic --extra-cflags="-fPIC -fvisibility=hidden -O2 -g" --extra-cxxflags="-fPIC -fvisibility=hidden -O2 -g" --extra-ldflags="-fPIC"
      
      - name: Compile FFmpeg
        run: make
      
      - name: Install FFmpeg
        run: make install
      
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-macos
          path: |
            ${{ github.workspace }}/installdir/lib/
            ${{ github.workspace }}/installdir/include/
          retention-days: 90
          overwrite: true

