name: Create Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Workflow Run
        id: get-run
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        run: |
          latest_run=$(gh run list --workflow=build.yml --limit 1 --json databaseId,status --jq '.[] | select(.status == "completed") | .databaseId')
          echo "run_id=$latest_run" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          run-id: ${{ steps.get-run.outputs.run_id }}
      
      - name: debug
        run: ls ffmpeg-libs-linux

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ffmpeg-libs-linux
            ffmpeg-libs-macos
            ffmpeg-libs-win
          tag_name: ${{ github.event.inputs.release-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
